### ISSUE TITLE
Failed to demangle superclass of RxCollectionViewSectionedReloadDataSource from mangled name '13RxDataSources023CollectionViewSectionedB6SourceCyxG'

### ISSUE THREAD

**Issue by krystlemaelabio** [RxSwiftCommunity/RxDataSources#306]
Runtime error in our app with RxDataSources version 4.0.0.

**Comment by kzaher** [comment]
We've released 4.0.1

Swift toolchain messed up static linking.

**Comment by krystlemaelabio** [comment]
Thanks, will check it.

**Comment by thomas3687** [comment]
Issue still persists with 4.0.1 or master vis Swift Package Manager and Xcode 11 Beta 2:

failed to demangle superclass of RxTableViewSectionedAnimatedDataSource from mangled name '13RxDataSources018TableViewSectionedB6SourceCyxG'

**Comment by clementprem** [comment]
Still blocked in Xcode 11 Beta 3 

```
failed to demangle superclass of FlatMap from mangled name '7RxSwift8ProducerCy7ElementAA25ObservableConvertibleTypePQy_G'
```

@kzaher can you please reopen this

**Comment by gabrielPeart** [comment]
Having the same issue @kzaher

**Comment by Nickersoft** [comment]
Noticing this on the XCode 11 public release as well (11A420a)

**Comment by thomas3687** [comment]
@gabrielPeart @Nickersoft do you have multiple targets to which you have linked the swift package? E.g. an internal framework which you use in different extensions?

I solved this problem in order to just link the package to one target. In my case just to my shared internal framework. I had linked it before to both, to my framework and to the main app.

**Comment by clementprem** [comment]
setting `DEAD_CODE_STRIPPING=No` in build settings fixed the problem.

**Comment by zdnk** [comment]
> setting `DEAD_CODE_STRIPPING=No` in build settings fixed the problem.

this probably doesnt fix the `demangle` error does it?

I have the same issue when linking same dependency into multiple targets in project (eg. app and framework when the app has also dependency on the framework)

**Comment by Arcovv** [comment]
@zdnk Me too

**Comment by csense** [comment]
@zdnk Me too

**Comment by kwakueshun** [comment]
Obligatory "Me too"

**Comment by kaweerutk** [comment]
"Me Too" v4.5.0

**Comment by banane** [comment]
ditto (hi @kwakueshun )

**Comment by vmzhivetyev** [comment]
me too

**Comment by mohamede1945** [comment]
My solution to this problem is to only add it to one library. If I added it to 2 libraries or 1 library and the app, I'll get the crash.

**Comment by quentinfasquel** [comment]
@mohamede1945 I am facing this issue today. (using Xcode 12, but possibly would have the same issue with Xcode 11)

I am using RxSwift/Relay/Cocoa amongst several app "modules" divided in separate frameworks. The solution I found is to have an Rx.framework which static links with all 3 libraries defined in Package.swift
However, each of these frameworks have their own Unit Test target in Xcode, which sometimes rely on RxTest...

The thing is RxTest statically links with RxSwift and we end up having RxSwift symbols in both Rx.framework & Test-target.

Which ends up with the issue of demangling superclasses...
