### ISSUE TITLE
[Warning] The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0...

### ISSUE THREAD

**Issue by backslash-f** [RxSwiftCommunity/RxDataSources#378]
Xcode 12: `The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99.`

Support for iOS 8 seems to be gone for good.

Any change to bump you minimum deployment version?

Thanks.

Ah, it actually gives me an error too and I'm unable to build:
```
The package product 'RxSwift' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0
The package product 'RxCocoa' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0
```

![Screen Shot 2020-10-28 at 15 26 34](https://user-images.githubusercontent.com/664951/97449462-fafe6500-1931-11eb-89c2-7da830139de2.png)

**Comment by PatrickKaalund** [comment]
Any news on this issue?

**Comment by freak4pc** [comment]
Fixed in 5.0.0 @cameroncooke

**Comment by apvex** [comment]
Nop! I still have the problem with Xcode 12.4 and RxSwift 5.1.2

**Comment by cotchoninha** [comment]
I'm also having this issue =/
